### PR TITLE
Matomo fork update

### PR DESCRIPTION
**Pull request by felipecabargas**
Fixes https://optimere.atlassian.net/browse/MON-3954

### CODE REVIEW

**Comment by serch** [comment]
@felipecabargas should this be reviewed or is it still WIP?

**Comment by serch** [comment]
@felipecabargas https://github.com/Monsido/piwik-ruby-api/pull/16#issuecomment-1274391566 ?

**Comment by felipecabargas** [comment]
Still wip @serch

**Comment by serch** [comment]
@felipecabargas that's totally fine, I'll mark it as draft 👌

**Comment by serch** [comment]
@felipecabargas could you please create a jira task to continue with this? thanks

**Comment by serch** [comment]
@felipecabargas unless we have plans to work on this in Q3 I'd say we close the PR

**Comment by serch** [comment]
@felipecabargas I'll close the PR, feel free to reopen if you plan on working on it

**Pull request closed without merging**
